name: Check iPhone Price

on:
  schedule:
    - cron: "0 */4 * * *"   # ogni 4 ore
    - cron: "0 9 * * *"     # alle 09:00 (report giornaliero)
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install requests beautifulsoup4 playwright
          playwright install chromium

      - name: Download previous state
        uses: actions/download-artifact@v4
        with:
          name: price-state
          path: .
        continue-on-error: true

      - name: Run price watcher
        run: |
          if [ "$(date +%H)" = "09" ]; then
            python price_watcher.py --always
          else
            python price_watcher.py
          fi
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Upload state
        uses: actions/upload-artifact@v4
        with:
          name: price-state
          path: price_state.json

      - name: Upload debug if present
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-html
          path: last_response.html
          if-no-files-found: ignore
